name: Build and Test Angular App

on:
  push:
    branches: 
      - main
      - development
  pull_request:
    branches: 
      - main

jobs:
  build-deploy:
    name: Build and deploy angular app
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js version 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install depencies
      run: npm install --force
    
    - name: Build the app
      run: npm run build --if-present

    # - name: Run unit test with kama
    #   run : npm test -- --browsers=ChromeHeadless --watch=false

    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        dockerfile: Dockerfile
        push: false
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops-skills-ui:v1.0.0
    
    - name: Login to Docker
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Push to docker Hub
      uses: docker/build-push-action@v3
      with:
        context: .
        dockerfile: Dockerfile
        push: true
        platforms: linux/amd64
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops-skills-ui:v1.0.0
